---
secops_user: ls22sistem
web_user: ls22web
th_user: ls22th
sp_user: ls22sp
bank_user: ls22bank

#user_create rolünde oluşturulmuştur.
#admin_user: root
#admin_new_password: Parslan123!!

#keys_directory: "../templates/" Ahtapot123!! all users password
deb_secops_pass: $6$9G5p7kC1rrY0/3ZZ$NZtAd4/AfqQtxBCyeQ7gyPf1n8YYlUCOutZ84ZECCtNvUwodAfGOrzbkUVzKwf.K/N7Oh08U7AV8HDMj5MfHT.
yum_secops_pass: $6$arQ6nh1bzG0X8Sgk$eL7j.HtnTlWW0HjJ3D4gS8iLNFA/EGSMOK1gbxAiQqUDUJkaHrTMM9wNATVK7Vdyktj7a74yE.9IlSWBgQ6i70

deb_web_pass: $6$LiZ2SRq/P8Is3DPx$LtPub1TsgGyf6B0ucvIa5u/NeZzjLBTByjEMdbiFHZHpxxdAIiw3nd80jvYRa.4/ZNd43/n23ABZz/CyepdIa/ #Ahtapot123!!
yum_web_pass: $6$3TMYknw4BlljSdkJ$tdnFTBTaozkqvDcYH0sbvUVWT9PwiD5aymJtWXPx00QXYggCzP3AD3.MDB57fzcCxydrq7x4.P1QmSGWuuQ9p/ #Ahtapot123!!

yum_th_pass: $6$LmwXVIMiu0./0js0$sYYAtI3bS.2leyBuN3p08iZwRixG2IT64kaVXG49Oz.sO.yuuXJAm7vWF0XmZiVlbzQFspJkJ8Hf.x4KiyH9r1 #Ahtapot123!!
deb_th_pass: $6$VjiHKrBlAKSgPZ11$eCR2HoasFGnqbes3ngFqALDVg/nn4U9CgS0Vf0MZlZEb7nU3y.EKi8IXnht0MNWM2thiK0TU0SyAvVpdEO0Hg0 #Ahtapot123!!

yum_root_pass: $6$kaYdw82PJB.f6pfD$ISeAH3bd.WvHZ2iUSodjbLvU2eJeK8Dr.0EWa/IcYtj/yPh4MO9zFtYOeQoWHarqmcKiDt/cMcSJII3yic9Kv. #Pars123!!
deb_root_pass: $6$l8lcXppzuskBYuDd$.Dddkzp90PVYFqS6lx216Lcu7xwJxAY9g1gyAuQuuidTq6Co4.YFigRY7bC9o99y8l4.HphSqYf.sq/V9PQ1i1 #Pars123!!

yum_sp_pass: $6$qtl2fLzBSpvoavaw$oOiqykUg5gCpDPPBVaZ0N9OI61.cUp/5sTpV4f7zUJHwZu4Z9DFYu1BkvAlJVZIygMgWRxFIIBaS/JP4uMez2. #Ahtapot123!!
deb_sp_pass: $6$ikfy9oI1DZo1BN1G$Mf3NHIdkCDyKUuWznpQsl9WjlWGDRxQ7WSFmZCfE/tEiJt4c6azhNUlzGXP4Hb26bPTfAGoZIH.3eVtFgBM/Z/ #Ahtapot123!!

deb_bank_pass: $6$l0ngcLKFr.IZOBu1$v6zR7GJ1/h9ezWhUkMWyb9pHQ9/4FeoEfzIYfRNY68FgzyGq/v.giVTTDjlACSYOt3EFscF2U5Aeh16t4O4qI
yum_bank_pass: $6$/BYB8nfx./0j4S3h$tCL0tcZ2y00NBNy9mnHFEaaIbKZhUb0avDSIYk5IjO9hvy0ftVTu7vYbsh7SwduUqAze9tKcMXv58QMLwOXm3
